version: 2

models:
  - name: stg_product
    description: Staging table for products.

    columns:
      - name: product_id
        tests:
          - unique
          - not_null

      - name: product_subcategory_id

      - name: product_number
        tests:
          - unique
          - not_null

      - name: product_name
        tests:
          - not_null

      - name: standard_cost

      - name: list_price

      - name: sell_start_date
        tests:
          - not_null

  - name: stg_product_category
    description: Product categories.

    columns:
      - name: product_category_id
        tests:
          - unique
          - not_null

      - name: product_category_name
        tests:
          - unique
          - not_null

  - name: stg_product_subcategory
    description: Product subcategories.

    columns:
      - name: product_subcategory_id
        tests:
          - unique
          - not_null

      - name: product_category_id
        tests:
          - relationships:
              to: ref('stg_product_category')
              field: product_category_id

      - name: product_subcategory_name
        tests:
          - not_null

  - name: stg_product_inventory
    description: Product inventory.

    columns:
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_product')
              field: product_id

      - name: location_id

      - name: quantity

  - name: stg_product_list_price_history
    description: Product list price history.

    columns:
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_product')
              field: product_id

      - name: start_date
        tests:
          - not_null

  - name: stg_product_cost_history
    description: Product cost history.

    columns:
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_product')
              field: product_id

      - name: start_date
        tests:
          - not_null