version: 2

sources:
  - name: raw_production
    description: "Raw product data from AdventureWorks"
    database: adventureworks-pipeline-501611
    schema: raw

    tables:
      - name: product
      - name: productsubcategory
      - name: productcategory
      - name: productmodel
      - name: productinventory
      - name: location
      - name: unitmeasure
      - name: productcosthistory
      - name: productlistpricehistory